name: 🛠️ Sync Binary from Main Repo

on:
  schedule:
    - cron: '0 0 * * *'  # ⏰ Runs daily at midnight UTC
  workflow_dispatch:      # 🚀 Manual trigger support

jobs:
  fetch-latest-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test repo
        uses: actions/checkout@v3

      - name: Get latest release tag
        id: get_release
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/amaraoussama94/gestion_stock_c/releases/latest | jq -r .tag_name)
          echo "Latest tag: $LATEST_TAG"
          echo "TAG=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Download binary from release
        run: |
          mkdir -p build/
          curl -L -o ./build/gestion_stock \
            https://github.com/amaraoussama94/gestion_stock_c/releases/download/${{ steps.get_release.outputs.TAG }}/gestion_stock
          chmod +x ./build/gestion_stock

      - name: Commit updated binary (if needed)
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "ci-bot@example.com"
          git config --global user.name "CI Sync Bot"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add build/gestion_stock
          git commit -m "🤖 Sync latest binary from gestion_stock_c [${{ steps.get_release.outputs.TAG }}]" || echo "No changes to commit"
          git push

